version: "1.0.2-{build}"
skip_tags: true
image: Ubuntu2004
clone_depth: 1
branches:
  only:
    - master
    - /rc\/([\d\w\-\.]+)/
environment:
  PY_VER: 3.11
init:
  - sh: source $HOME/venv$PY_VER/bin/activate
  - sh: export TOX_DISCOVER="$HOME/venv3.7/bin/python:$HOME/venv3.8/bin/python:$HOME/venv3.9/bin/python:$HOME/venv3.10/bin/python:$HOME/venv3.11/bin/python"
  - sh: python --version
build: false
install:
  - python -m pip install "pip>=21" "wheel>=0.37" || python -c "print('')"
  - python -m pip install --upgrade --prefer-binary "tox<4.0.0"
test_script:
  - python -m tox